#=========================================================================
# mkdocs Configuration
#=========================================================================

site_name:   'ECE 6745 Complex Digital ASIC Design'
site_author: 'Christopher Batten'

# Repository

repo_name:   'cornell-ece6745/ece6745-mkdocs'
repo_url:    'https://github.com/cornell-ece6745/ece6745-mkdocs'

# Copyright

copyright:   'Copyright &copy; 2024 Christopher Batten'

# Configuration

theme:
  name:       'material'
  custom_dir: 'theme/'
  language:   'en'
  favicon:    'img/favicon.ico'
#  font:
#    text: 'Ubuntu'
#    code: 'Ubuntu Mono'
  palette:
    primary:  'blue'
    accent:   'indigo'
  features:
    - navigation.tabs
    - content.code.copy

# Extensions

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# markdown_extensions:
#   - pymdownx.arithmatex
#   - pymdownx.details
#   - toc:
#       permalink: true
#   - codehilite:
#       linenums: true

# Extras

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'js/extras.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  # pymdownx.arithmatex
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # Wavedrom
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/skins/default.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/wavedrom.min.js
  - js/wavedrom_loader.js


# Pages

nav:

  - 'Tutorials':
    - 'Tutorial 0: ECE Linux Server Remote Access': ece6745-tut00-remote-access.md
    - 'Tutorial 1: Linux Development Environment': ece6745-tut01-linux.md
    - 'Tutorial 2: Git Distributed Version Control System': ece6745-tut02-git.md

#    - 'Tutorial 5: ASIC Standard Cells': ece6745-tut05-asic-stdcells.md
#    - 'Tutorial 6: ASIC Front-End Flow': ece6745-tut06-asic-front-end.md
#    - 'Tutorial 7: ASIC Back-End Flow': ece6745-tut07-asic-back-end.md
#    - 'Tutorial 8: ASIC Automated Flow': ece6745-tut08-asic-auto.md
#    - 'Tutorial 9: TinyRV2 Accelerator RTL Design': ece6745-tut09-xcel-rtl.md
#    - 'Tutorial 10: SRAM Generators': ece6745-tut10-sram.md
#    - 'Tutorial 12: SPICE Simulation': ece6745-tut12-spice-sim.md
#    - 'Tutorial 13: DesignWare and Retiming': ece6745-tut13-dw.md

#  - 'Sections':
#    - 'Section 1: ASIC Front-End Flow': ece6745-sec01-asic-front-end.md
#    - 'Section 2: ASIC Back-End Flow': ece6745-sec02-asic-back-end.md
#    - 'Section 3: ASIC Automated Flow': ece6745-sec03-asic-auto.md
#    - 'Section 4: TinyRV2 Accelerator RTL Design': ece6745-sec04-xcel-rtl.md
#    - 'Section 5: SRAM Generators': ece6745-sec05-sram.md

  - 'Labs':
    - 'Lab 1: Full-Custom Inverter': ece6745-lab1.md
    - 'Lab 2: Standard-Cell Inverter': ece6745-lab2.md
    - 'Lab 3: TinyFlow Front End': ece6745-lab3.md
    - 'Lab 4: TinyFlow Back End': ece6745-lab4.md

  - 'Projects':
    - 'Project 1: TinyFlow Tape-Out':
      - "Part A: TinyFlow Standard Cells": ece6745-project1a.md
      - "Part B: TinyFlow Front End": ece6745-project1b.md
      - "Part C: TinyFlow Back End": ece6745-project1c.md

  - 'Misc':
    - 'Tinyflow 180nm Design Rules Manual': ece6745-tinyflow-180nm-drm.md
